---
name: Shellcheck

on:
  push:
    branches: [main]
    paths: ['**/*.sh', '.github/workflows/shellcheck.yml']
  pull_request:
    branches: [main]
    paths: ['**/*.sh', '.github/workflows/shellcheck.yml']

permissions:
  contents: read

jobs:
  shellcheck:
    name: Check shell scripts
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y shellcheck
      - name: shellcheck
        run: |
          git grep -l '^#\( *shellcheck \|!\(/bin/\|/usr/bin/env \)\(sh\|bash\|dash\|ksh\)\)' | xargs shellcheck
